### ISSUE TITLE
Unable to complete output ring starting at [...]. Last matching segment found ends at [...].

### ISSUE THREAD

**Issue by oli-clive-griffin** [mfogel/polygon-clipping#140]
I'm getting this error on trying to intersect these two polygons: ([viewer link](http://geojson.io/#map=18/-37.92817/175.44090))

It isn't really clear why this wouldn't be working. 

    "polygon-clipping": "^0.15.3",

```
Error: Unable to complete output ring starting at [175.4412230000001, -37.929121]. Last matching segment found ends at [175.441261917386, -37.92871399662434].
    at Function.factory (node_modules/polygon-clipping/dist/polygon-clipping.cjs.js:1252:21)
    at Operation.run (node_modules/polygon-clipping/dist/polygon-clipping.cjs.js:1776:30)
    at Object.intersection (node_modules/polygon-clipping/dist/polygon-clipping.cjs.js:1800:20)
    at Object.intersect (node_modules/@turf/intersect/dist/js/index.js:49:51)
```

**Comment by oli-clive-griffin** [comment]
the first thing that stands out is very different degrees of accuracy, could that be a factor?

**Comment by markstos** [comment]
This issue is fixed in the polygon-ts library:
https://github.com/luizbarboza/polyclip-ts

I recommend using it instead.
